trigger:
  branches:
    include:
      # - main
      - dev

variables:
  azureServiceConnection: "Azure subscription 1 (307f3351-f3f3-42f2-aa13-405cd075f673)"
  devFunctionAppName: "pdfFuncApp-Dev"
  prodFunctionAppName: "pdfFuncApp"
  artifactPath: "$(System.DefaultWorkingDirectory)/app/artifact"
  resourceGroup: "FinalTask-PDF-RG"

stages:
  - stage: Build
    displayName: "Build Application"
    jobs:
      - job: BuildFunctionApp
        displayName: "Build Azure Function App"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - checkout: self
            displayName: "Checkout Code"

          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.x"
              addToPath: true
            displayName: "Set up Python"

          - script: |
              echo "Installing dependencies..."
              pip install -r requirements.txt
            displayName: "Install Dependencies"

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)'
              artifactName: 'function-app-artifact'
              publishLocation: 'pipeline'
            displayName: "Publish Artifact"

  - stage: DeployToDev
    displayName: "Deploy to Development"
    dependsOn: Build
    jobs:
      - job: DeployFunctionApp
        displayName: "Deploy Azure Function App to DEV"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              artifactName: 'function-app-artifact'
              targetPath: "$(artifactPath)"
            displayName: "Download Artifact"

          - task: AzureCLI@2
            inputs:
              azureSubscription: "$(azureServiceConnection)"
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |

                echo "Starting the Dev Function App..."
                az functionapp start --name $(devFunctionAppName) --resource-group $(resourceGroup)
                
                pwd
                ls
                cd app 
                echo "Installing Azure Functions Core Tools..."
                npm install -g azure-functions-core-tools@4 --unsafe-perm true

                echo "Deploying Azure Function App to Dev..."
                func azure functionapp publish $(devFunctionAppName) --python
            displayName: "Deploy Function App to Dev"
            #pwd and ls are used for test purposes
  - stage: Approval
    displayName: "Manual Approval for Production"
    dependsOn: DeployToDev
    jobs:
      - job: Approval
        steps:
          - script: echo "Waiting for manual approval"
            displayName: "Manual Approval Step"

  - stage: DeployToProd
    displayName: "Deploy to Production"
    dependsOn: Approval
    jobs:
      - deployment: Deploy
        environment: "Prod"
        strategy:
          runOnce:
            deploy:
              steps:
              - task: DownloadPipelineArtifact@2
                inputs:
                  artifactName: 'function-app-artifact'
                  targetPath: "$(artifactPath)"
                displayName: "Download Artifact"

              - task: AzureCLI@2
                inputs:
                  azureSubscription: "$(azureServiceConnection)"
                  scriptType: bash
                  scriptLocation: inlineScript
                  inlineScript: |
                   
                    echo "Stopping the Dev Function App..."
                    az functionapp stop --name $(devFunctionAppName) --resource-group $(resourceGroup)

                    echo "Starting the Prod Function App..."
                    az functionapp start --name $(prodFunctionAppName) --resource-group $(resourceGroup)
                    
                    ls
                    
                    echo "cd to app "
                    cd app/artifact/app
 

                    echo "Installing Azure Functions Core Tools..."
                    npm install -g azure-functions-core-tools@4 --unsafe-perm true
                    
                     
                    echo "Deploying Azure Function App to Prod..."
                    func azure functionapp publish $(prodFunctionAppName) --python 

                displayName: "Deploy Function App to Prod"
                #pwd and ls are used for test purposes
