trigger:
  branches:
    include:
      - main
      - dev

variables:
  azureServiceConnection: "Azure subscription 1 (307f3351-f3f3-42f2-aa13-405cd075f673)"
  devFunctionAppName: "pdfFuncApp-Dev"
  prodFunctionAppName: "pdfFuncApp"
  packagePath: "$(Pipeline.Workspace)/s"
  resourceGroup: "FinalTask-PDF-RG"

stages:
  - stage: DeployToDev
    displayName: "Deploy to Development"

    jobs:
      - job: DeployFunctionApp
        displayName: "Deploy Azure Function App-DEV"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: "$(azureServiceConnection)"
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
              
                # echo "Starting the Dev Function App "
               
                # az functionapp start --name $(devFunctionAppName)  --resource-group $(resourceGroup)
                
                echo "Installing Azure Functions Core Tools..."
                npm install -g azure-functions-core-tools@4 --unsafe-perm true

                # echo "Deploying Azure Function App..."
                pwd
                func azure functionapp publish $(devFunctionAppName) --python
            displayName: "Deploy Function App to Dev"



  - stage: Approval
    displayName: "Manual Approval for Production"
    dependsOn: DeployToDev
    jobs:
      - job: Approval
        steps:
          - script: echo "Waiting for manual approval"
            displayName: "Manual Approval Step"

  - stage: DeployToProd
    displayName: "Deploy to Production"
    dependsOn: Approval
    jobs:
      - deployment: Deploy
        environment: "Prod"
        strategy:
          runOnce:
            deploy:
              steps:
              - task: AzureCLI@2
                inputs:
                  azureSubscription: "$(azureServiceConnection)"
                  scriptType: bash
                  scriptLocation: inlineScript
                  inlineScript: |

                    pwd
                    echo "Changing directory to project root..."
                    cd $(packagePath)
                    pwd
                    echo "Installing Azure Functions Core Tools..."
                    npm install -g azure-functions-core-tools@4 --unsafe-perm true

                    echo "Deploying Azure Function App to Prod..."
                    func azure functionapp publish $(prodFunctionAppName) --python --source $(packagePath)
                displayName: "Deploy Function App to Prod"


                    # echo "Stopping the Dev Function App..."
                    # az functionapp stop --name $(devFunctionAppName) --resource-group $(resourceGroup)

                    # echo "Starting the Prod Function App..."
                    # az functionapp start --name $(prodFunctionAppName) --resource-group $(resourceGroup)