trigger:
  branches:
    include:
      - main
      - dev

variables:
  azureServiceConnection: "Azure subscription 1 (307f3351-f3f3-42f2-aa13-405cd075f673)"
  devFunctionAppName: "pdfFuncApp-Dev"
  prodFunctionAppName: "pdfFuncApp"
  packagePath: "$(Pipeline.Workspace)/drop/functionapp.zip"
  resourceGroup: "FinalTask-PDF-RG"

stages:

  - stage: Build
    displayName: "Build and Package Application"

    jobs:
      - job: Build
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.x"
              addToPath: true

          - script: |
              python -m venv env
              source env/bin/activate
              pip install -r requirements.txt
            displayName: "Install Dependencies"

          - script: |
              zip -r $(Build.ArtifactStagingDirectory)/functionapp.zip .
            displayName: "Package Application"

          - publish: $(Build.ArtifactStagingDirectory)/functionapp.zip
            artifact: drop

  - stage: DeployToDev
    displayName: "Deploy to Development"
    dependsOn: Build

    jobs:
      - job: DeployFunctionApp
        displayName: "Deploy Azure Function App-DEV"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: "$(azureServiceConnection)"
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "Starting the Dev Function App "
               
                # az functionapp start --name $(devFunctionAppName)  --resource-group $(resourceGroup)
                
                # echo "Installing Azure Functions Core Tools..."
                # npm install -g azure-functions-core-tools@4 --unsafe-perm true

                # echo "Deploying Azure Function App..."

                # func azure functionapp publish $(devFunctionAppName) --python
            displayName: "Deploy Function App to Dev"



  - stage: Approval
    displayName: "Manual Approval for Production"
    dependsOn: DeployToDev
    jobs:
      - job: Approval
        steps:
          - script: echo "Waiting for manual approval"
            displayName: "Manual Approval Step"

  - stage: DeployToProd
    displayName: "Deploy to Production"
    dependsOn: Approval
    jobs:
      - deployment: Deploy
        environment: Prod
        strategy:
          runOnce:
            deploy:
              steps:
              - task: AzureCLI@2
                inputs:
                  azureSubscription: "$(azureServiceConnection)"
                  scriptType: bash
                  scriptLocation: inlineScript
                  inlineScript: |
                    echo "Stopping the Dev Function App..."
                    az functionapp stop --name $(devFunctionAppName) --resource-group $(resourceGroup)

                    echo "Starting the Prod Function App..."
                    az functionapp start --name $(prodFunctionAppName) --resource-group $(resourceGroup)

                    echo "Installing Azure Functions Core Tools..."
                    npm install -g azure-functions-core-tools@4 --unsafe-perm true

                    echo "Deploying Azure Function App to Prod..."
                    func azure functionapp publish $(prodFunctionAppName) --python
                displayName: "Deploy Function App to Prod"