trigger:
  branches:
    include:
      - main
      # - dev

variables:
- group: TerraformVars  


stages:

  - stage: Build
    displayName: "Build Application"
    jobs:
      - job: BuildFunctionApp
        displayName: "Build Azure Function App"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - checkout: self
            displayName: "Checkout Code"

          - task: UsePythonVersion@0
            inputs:
              versionSpec: "3.x"
              addToPath: true
            displayName: "Set up Python"

          - script: |
              echo "Installing dependencies..."
              pip install -r requirements.txt
            displayName: "Install Dependencies"

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)'
              artifactName: 'function-app-artifact'
              publishLocation: 'pipeline'
            displayName: "Publish Artifact"



# Stage 1: Deploy TF Infrastructure for Dev
  - stage: Dev_Infra
    displayName: "Deploy TF Infra for Dev"
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/dev')
    jobs:
    - job: Terraform_Dev
      displayName: "Deploying Dev env"
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - checkout: self


        - task: Bash@3
          displayName: "Install Azure CLI"
          inputs:
            targetType: 'inline'
            script: |
              curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
              az --version

        - task: Bash@3
          displayName: "Azure Login with Service Principal"
          inputs:
            targetType: 'inline'
            script: |
              az login --service-principal \
                --username $(ARM_CLIENT_ID) \
                --password $(ARM_CLIENT_SECRET) \
                --tenant $(ARM_TENANT_ID)
              az account set --subscription $(ARM_SUBSCRIPTION_ID)
              az account show
          env:
            ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
            ARM_CLIENT_ID: $(ARM_CLIENT_ID)
            ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
            ARM_TENANT_ID: $(ARM_TENANT_ID)


        - task: TerraformInstaller@0
          inputs:
            terraformVersion: '1.9.8'

        - task: Bash@3
          displayName: 'Run Terraform Commands'
          inputs:
            targetType: 'inline'
            script: |
              cd terraform/Dev 
              pwd
              ls
              terraform init -lock=false
              terraform validate -no-color
              terraform plan -no-color -input=false
              terraform apply --auto-approve
          env:
              TF_VAR_TELEGRAM_BOT_TOKEN: $(TF_VAR_TELEGRAM_BOT_TOKEN)
              TF_VAR_TELEGRAM_CHAT_ID: $(TF_VAR_TELEGRAM_CHAT_ID)
              TF_VAR_DISCORD_WEBHOOK_URL: $(TF_VAR_DISCORD_WEBHOOK_URL)
              TF_VAR_subscription_id: $(ARM_SUBSCRIPTION_ID)
              TF_VAR_client_id: $(ARM_CLIENT_ID)
              TF_VAR_client_secret: $(ARM_CLIENT_SECRET)
              TF_VAR_tenant_id: $(ARM_TENANT_ID)


  - stage: Approval
    displayName: "Manual Approval for Production"
    dependsOn: Dev_Infra
    jobs:
      - job: Approval
        steps:
          - script: echo "Waiting for manual approval"
            displayName: "Manual Approval Step"


  - stage: DeployFuncToDev
    displayName: "Deploy Function to Development"
    dependsOn: Approval
    jobs:
      - deployment: Deploy
        environment: "Dev"
        strategy:
          runOnce:
            deploy:
              steps:
              - task: DownloadPipelineArtifact@2
                inputs:
                  artifactName: 'function-app-artifact'
                  targetPath: "$(artifactPath)"
                displayName: "Download Artifact"

              - task: AzureCLI@2
                inputs:
                  azureSubscription: "$(azureServiceConnection)"
                  scriptType: bash
                  scriptLocation: inlineScript
                  inlineScript: |
                
                    echo "Starting the Prod Function App..."
                    az functionapp start --name $(devFunctionAppName) --resource-group $(resourceGroup)
                    
                    ls
                    
                    echo "cd to app "
                    cd app/artifact/app
 

                    echo "Installing Azure Functions Core Tools..."
                    npm install -g azure-functions-core-tools@4 --unsafe-perm true
                    
                     
                    echo "Deploying Azure Function App to Prod..."
                    func azure functionapp publish $(prodFunctionAppName) --python 

                displayName: "Deploy Function App to Dev"























  # - stage: DeployToDev
  #   displayName: "Deploy to Development"
  #   dependsOn: Build
  #   jobs:
  #     - job: DeployFunctionApp
  #       displayName: "Deploy Azure Function App to DEV"
  #       pool:
  #         vmImage: "ubuntu-latest"
  #       steps:
  #         - task: DownloadPipelineArtifact@2
  #           inputs:
  #             artifactName: 'function-app-artifact'
  #             targetPath: "$(artifactPath)"
  #           displayName: "Download Artifact"

  #         - task: AzureCLI@2
  #           inputs:
  #             azureSubscription: "$(azureServiceConnection)"
  #             scriptType: bash
  #             scriptLocation: inlineScript
  #             inlineScript: |

  #               echo "Starting the Dev Function App..."
  #               az functionapp start --name $(devFunctionAppName) --resource-group $(resourceGroup)
                
  #               pwd
  #               ls
  #               cd app 
  #               echo "Installing Azure Functions Core Tools..."
  #               npm install -g azure-functions-core-tools@4 --unsafe-perm true

  #               echo "Deploying Azure Function App to Dev..."
  #               func azure functionapp publish $(devFunctionAppName) --python
  #           displayName: "Deploy Function App to Dev"
            





# # Stage 2: Deploy to Prod
# - stage: Prod
#   displayName: "Deploy to Production Environment"
#   dependsOn: Dev  
#   jobs:
#     - deployment: Terrafrom_Prod
#       displayName: "Deploying Prod env"
#       pool:
#         vmImage: 'ubuntu-latest'
#       environment:
#             name: 'Prod'  
#       strategy:
#         runOnce:
#           deploy:
#             steps:
#                   - checkout: self

#                   - task: Bash@3
#                     displayName: "Install Azure CLI"
#                     inputs:
#                       targetType: 'inline'
#                       script: |
#                         curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
#                         az --version

#                   - task: Bash@3
#                     displayName: "Azure Login with Service Principal"
#                     inputs:
#                       targetType: 'inline'
#                       script: |
#                         az login --service-principal \
#                           --username $(ARM_CLIENT_ID) \
#                           --password $(ARM_CLIENT_SECRET) \
#                           --tenant $(ARM_TENANT_ID)
#                         az account set --subscription $(ARM_SUBSCRIPTION_ID)
#                         az account show
#                     env:
#                       ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
#                       ARM_CLIENT_ID: $(ARM_CLIENT_ID)
#                       ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
#                       ARM_TENANT_ID: $(ARM_TENANT_ID)


#                   - task: TerraformInstaller@0
#                     inputs:
#                       terraformVersion: '1.9.8'



#                   - task: Bash@3
#                     displayName: 'Run Terraform Commands'
#                     inputs:
#                       targetType: 'inline'
#                       script: |
#                         cd terraform/Prod
#                         pwd 
#                         ls
#                         terraform init -lock=false
#                         terraform validate -no-color
#                         terraform plan -no-color -input=false
#                         terraform apply --auto-approve

#                     env:
#                         TF_VAR_TELEGRAM_BOT_TOKEN: $(TF_VAR_TELEGRAM_BOT_TOKEN)
#                         TF_VAR_TELEGRAM_CHAT_ID: $(TF_VAR_TELEGRAM_CHAT_ID)
#                         TF_VAR_DISCORD_WEBHOOK_URL: $(TF_VAR_DISCORD_WEBHOOK_URL)
#                         TF_VAR_subscription_id: $(ARM_SUBSCRIPTION_ID)
#                         TF_VAR_client_id: $(ARM_CLIENT_ID)
#                         TF_VAR_client_secret: $(ARM_CLIENT_SECRET)
#                         TF_VAR_tenant_id: $(ARM_TENANT_ID) 
